#version "3.9"

# sem banco de dados
services:
  app:

    # configs build
    build: 
      context: ../
      dockerfile: Docker/Dockerfile
      
    network_mode: "host"

    # portas de acesso (user:docker)
    ports:
      - "5000:5000"
      - "3000:3000"
    # diretorios a serem criados
    volumes:
      - ../:/bpi
