#version "3.9"

# sem banco de dados
services:
  btree:

    # configs build
    build: 
      context: .
      network: host

    # portas de acesso (user:docker)
    ports:
      - "5000:5000"

    # diretorios a serem criados
    volumes:
      - ./:/bpi




